logging:
  level:
    .: error
    root: info
    org.springframework: INFO
    org.springframework.security: INFO
    com.acevedo: DEBUG

---
spring:
   profiles: dev
   application:
        name: dental
   datasource:
        driverClassName: org.mariadb.jdbc.Driver
        url: jdbc:mysql://localhost:3306/paciente
        username: root
        password: root
        driver-class-name: org.mariadb.jdbc.Driver
        initialization-mode: always             
   jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect        
server:
    port: 8080
    
---
spring:
   profiles: aws
   application:
        name: dental
   datasource:
        driverClassName: org.mariadb.jdbc.Driver
        url: jdbc:mysql://database-1.csxxycd3qghh.us-east-1.rds.amazonaws.com:3306/paciente
        username: dental
        password: pa55w0rd
        driver-class-name: org.mariadb.jdbc.Driver
        initialization-mode: never                      
server:
    port: 5000